#!/bin/bash

cd ~/EE/MyJAVA/0
#cd ~/EE/Win_MyJAVA/0
# bash ./j0 386 CopyFile FIRST.TXT SECOND.TXT
#bash ./j0 895 NIOCopy NIOCopy.java NIOCopy.txt
#bash ./j0 896 ShowFile test.txt

bash ./j0 282 MethNestTry

KodVyp=$?
if [ $KodVyp -ne 0 ]; then
  echo Выполнено с ошибкой
  set -e
fi



